-- Migration: 20251104202033_InitialCreate
-- Create Submission and Appeal tables for SubmissionService

-- Create Submission table
CREATE TABLE IF NOT EXISTS "Submission" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "ContestNoticeId" integer NOT NULL,
    "ParticipantId" integer NOT NULL,
    "DateTime" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CoverLetter" text NULL,
    "Comment" text NULL,
    "DocsPackageIsValid" boolean NULL,
    "SubmissionState" character varying(100) NULL,
    CONSTRAINT "PK_Submission" PRIMARY KEY ("Id")
);

-- Create Appeal table
CREATE TABLE IF NOT EXISTS "Appeal" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "SubmissionId" integer NOT NULL,
    "DateTime" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CoverLetter" text NULL,
    "AppealState" character varying(100) NULL,
    "Comment" text NULL,
    CONSTRAINT "PK_Appeal" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Appeal_Submission_SubmissionId" FOREIGN KEY ("SubmissionId") REFERENCES "Submission" ("Id") ON DELETE CASCADE
);

-- Create unique index for 1:1 relationship
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Appeal_SubmissionId" ON "Appeal" ("SubmissionId");

-- Add foreign key constraints to ContestNotice and User tables (if they exist)
-- Uncomment these if ContestNotice and User tables exist in the same database:
-- ALTER TABLE "Submission" ADD CONSTRAINT "FK_Submission_ContestNotice" FOREIGN KEY ("ContestNoticeId") REFERENCES "ContestNotice" ("Id");
-- ALTER TABLE "Submission" ADD CONSTRAINT "FK_Submission_User" FOREIGN KEY ("ParticipantId") REFERENCES "User" ("Id");

-- Insert migration record to track that this migration has been applied
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251104202033_InitialCreate', '9.0.10')
ON CONFLICT ("MigrationId") DO NOTHING;

