// <auto-generated />
using System;
using ContestService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ContestService.Infrastructure.Migrations
{
    [DbContext(typeof(ContestDbContext))]
    partial class ContestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ContestService.Domain.Entities.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Attachment", (string)null);
                });

            modelBuilder.Entity("ContestService.Domain.Entities.ContestDocsPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttachmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<int>("ContestNoticeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("ContestNoticeId");

                    b.ToTable("ContestDocsPackage", (string)null);
                });

            modelBuilder.Entity("ContestService.Domain.Entities.ContestNotice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompetitionType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<string>("Goal")
                        .HasColumnType("text");

                    b.Property<int>("OrganizerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("ContestNotice", (string)null);
                });

            modelBuilder.Entity("ContestService.Domain.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Event", (string)null);
                });

            modelBuilder.Entity("ContestService.Domain.Entities.EventStage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("timestamp");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("timestamp");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("PreviousStageId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("PreviousStageId");

                    b.ToTable("EventStage", (string)null);
                });

            modelBuilder.Entity("ContestService.Domain.Entities.EventStageCriteria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EventStageId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("IsActiveUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("MinimumThresholdScore")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("EventStageId");

                    b.ToTable("EventStageCriteria", (string)null);
                });

            modelBuilder.Entity("ContestService.Domain.Entities.ContestDocsPackage", b =>
                {
                    b.HasOne("ContestService.Domain.Entities.Attachment", "Attachment")
                        .WithMany("ContestDocsPackages")
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContestService.Domain.Entities.ContestNotice", "ContestNotice")
                        .WithMany("ContestDocsPackages")
                        .HasForeignKey("ContestNoticeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attachment");

                    b.Navigation("ContestNotice");
                });

            modelBuilder.Entity("ContestService.Domain.Entities.ContestNotice", b =>
                {
                    b.HasOne("ContestService.Domain.Entities.Event", "Event")
                        .WithMany("ContestNotices")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("ContestService.Domain.Entities.EventStage", b =>
                {
                    b.HasOne("ContestService.Domain.Entities.Event", "Event")
                        .WithMany("EventStages")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContestService.Domain.Entities.EventStage", "PreviousStage")
                        .WithMany("NextStages")
                        .HasForeignKey("PreviousStageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Event");

                    b.Navigation("PreviousStage");
                });

            modelBuilder.Entity("ContestService.Domain.Entities.EventStageCriteria", b =>
                {
                    b.HasOne("ContestService.Domain.Entities.EventStage", "EventStage")
                        .WithMany("EventStageCriterias")
                        .HasForeignKey("EventStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventStage");
                });

            modelBuilder.Entity("ContestService.Domain.Entities.Attachment", b =>
                {
                    b.Navigation("ContestDocsPackages");
                });

            modelBuilder.Entity("ContestService.Domain.Entities.ContestNotice", b =>
                {
                    b.Navigation("ContestDocsPackages");
                });

            modelBuilder.Entity("ContestService.Domain.Entities.Event", b =>
                {
                    b.Navigation("ContestNotices");

                    b.Navigation("EventStages");
                });

            modelBuilder.Entity("ContestService.Domain.Entities.EventStage", b =>
                {
                    b.Navigation("EventStageCriterias");

                    b.Navigation("NextStages");
                });
#pragma warning restore 612, 618
        }
    }
}
